#!/bin/bash

#### CONFIG - CHANGE THESE ####
source /etc/pastit/.env
# Set this to your zipline url*
og_url="${host}"
URL="${host}/api/upload"
if [ -z "$*" ]; then
echo "No target file selected"
exit 0
fi
## *If your host machine is the same machine you are running this script on, I suggest using http://localhost:{PORT NUMBER} (obviously replace {PORT NUMBER} with the port number you setup zipline on) instead, since it is easier.

# Set this to your zipline authorization token (I found this in the generated sharex config file)
#### END CONFIG ####
#### SCRIPT START ####
# Check if text is provided vi
# Write data to the file

# API endpoint and headers

# Sending the request using curl and capturing the response
response=$(curl -s -X POST -H "Authorization: $authorization_token" \
                        -H "Format: random" \
                        -H "Original-Name: true" \
                        -F "file=@$1" \
                        "$URL")
                        
# just the URL from the JSON response
file_url=$(echo "$response" | jq -r '.files[0]')

# Replace /u/ with /code/ in the URL

# Replace localhost:3000 with share.harryeffingpotter.com/api/upload
modified_url=$(echo "$file_url" | sed "s!http://!!" | sed  "s!${og_url}!${targetdomain}!" | sed "s!/u/!/r/!")
# Output the modified URL

if [[ ! "$modified_url" =~ ^https:// ]]; then
    modified_url="https://${modified_url}"
fi
echo "$modified_url"

# Clean up: Remove temporary file

